### ISSUE TITLE
Fullscreen with multi-screen works not properly 

### ISSUE THREAD

**Issue by chs040701** [Francesco149/weebp#2]
I have 2 screens, one is 1920*1080, another is 3840*2160.
the first screen coordinates is [-1920,0],[0,1080],
and the second is [0,3840],[0,2160]
Now the full screen position is [-1920,1920],[0,2160]

**Comment by Francesco149** [comment]
```--fullscreen``` is supposed to fill one of the monitors, the one the window is currently in. if you want a background that spans both monitors you will have to set coordinates manually with the move command for now. maybe i'll consider adding another kind of fullscreen, like maybe ```--multimonitor``` or something that spans all monitors

**Comment by chs040701** [comment]
Thanks.
But it seems --fullscreen does not behavior as expected. Wherever I put the window, fullscreen will fill 1080p screen with 2160p size.

**Comment by Francesco149** [comment]
hm, interesting, I remember testing on my dual monitor (1280x1024 and 1920x1080) and it was working as expected, but I guess i'll re-test ```--fullscreen``` as well

**Comment by Francesco149** [comment]
ok i see the problem with --fullscreen, the coordinates used in ```wp mv``` seem to be always positive even on multimonitor setup, which doesn't match the coordinates returned when i query the monitors (for example my 2nd monitor is monitor: -1280 0 0 1024). i'm currently testing if MapWindowPoints from the desktop window to the root window is what i want and it seems like it behaves as it should

but there's another issue, for some reason it always wants to put it on my 2nd monitor, so maybe I'll use the cursor position to figure out which monitor instead of using MonitorFromWindow which doesn't seem to work

**Comment by Francesco149** [comment]
ok i fixed it and also added a --panoramic option to make a window fill all monitors
